- name: Onboard Product Team in AAP
  hosts: localhost
  gather_facts: false
  tasks:
   - name: Create Organization for Product
     ansible.platform.organization:
        aap_hostname: 192.168.122.151
        aap_username: "admin"
        aap_password: "redhat"
        name: test-org-prabhanjan
        description: This is my testing org
        state: present
