- name: Onboard Product Team in AAP
  hosts: localhost
  gather_facts: false
  tasks:

    - name: Create ibm verify authentication map
      ansible.platform.authenticator_map:
        name: test1
        aap_hostname: https://10.74.230.171
        aap_username: admin
        aap_password: redhat
        authenticator: ldap1
        revoke: false
        map_type: team
        role: Team Admin
        organization: org1
        team: team1
        triggers:
          attributes:
            groups:
              contains: team1
            join_condition: or
        state: present
        aap_validate_certs: false

